language: node_js
node_js:
  - "stable"
before script:
  - npm install coverage
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
script:
  coverage run -m unittest discover