language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master
install:
  npm install coverage
script:
  coverage run -m unittest discover